name: Build_Docker_Image

# Only triggered manually, and works only for feature/no-ref/ekalavya branch
on:
  workflow_dispatch:

env:
  IMAGE_NAME: ekalavya-io/ekalavya-scratch-editor

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/feature/no-ref/ekalavya'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIGET_AUTH }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:dev

